// Константы для генерации данных

const MIN_LIKES = 15;
const MAX_LIKES = 200;

const MIN_COMMENTS = 0;
const MAX_COMMENTS = 30;

const MIN_AVATAR = 1;
const MAX_AVATAR = 6;

const MIN_MESSAGE_COUNT = 1;
const MAX_MESSAGE_COUNT = 2;

const PHOTOS_COUNT = 25;

export { MIN_LIKES, MAX_LIKES, MIN_COMMENTS, MAX_COMMENTS, MIN_AVATAR, MAX_AVATAR, MIN_MESSAGE_COUNT, MAX_MESSAGE_COUNT, PHOTOS_COUNT };

